name: gdml-to-mesh
channels:
  - conda-forge
  - DLR-SC
  - defaults
dependencies:
  - python=3.11
  - cmake>=3.16
  - geant4>=11.0
  - opencascade>=7.6
  - hdf5
  - qt=5
  - pip
  - pip:
    - trimesh
    - matplotlib
    - numpy
    - scipy
    - -e .
